### ISSUE TITLE
libusb hotplug api unsupported in windows OS  ???

### ISSUE THREAD

**Issue by mmabluesky** [fpagliughi/yusb#1]
Hi ：

I tried to call this library on Windows, but it was prompted that hot swap is not supported. 
Is there any plan to support this in the future? ? ?

this is my code:
#[tauri::command]
pub fn get_usb_status(window: tauri::Window) -> Result<(), String>  {
    if usb::has_hotplug() {
        let context = match Context::new() {
            Ok(context) => context,
            Err(err) => {
                return Err(format!("Failed to create context: {}", err));
            }
        };

        let mut reg = Some(
            HotplugBuilder::new()
                .enumerate(true)
                .register(context.clone(), Box::new(HotPlugHandler::new(window)))
                .map_err(|e| e.to_string())?,
        );

        loop {
            context.handle_events(None).unwrap();
            if let Some(reg) = reg.take() {
                context.unregister_callback(reg);
                break;
            }
        }
        Ok(())
    } else {
        eprint!("libusb hotplug api unsupported");
        Ok(())
    }
}

**Comment by fpagliughi** [comment]
Unfortunately, no.

This library, and the chain of those that it was forked from - [rusb](https://crates.io/crates/rusb), [libusb-rs](https://crates.io/crates/libusb) are just wrappers around the C [libusb](https://github.com/libusb/libusb) library. It only exposes features that are available in the underlying library.

And there is no Windows hotplug support in libusb. There is, however, an Issue on its GitHub repo inquiring about Windows hotplug:
https://github.com/libusb/libusb/issues/86

But, as you might notice, that issue was opened in 2015, so I wouldn't hold out any hope that it might be coming soon.

**Comment by mmabluesky** [comment]
ok，I ，understand ，Thank u❤️
